### ISSUE TITLE
How do I use the same random value for each row

### ISSUE THREAD

**Issue by xiaodaigh** [johnmyleswhite/Volcanito.jl#24]
```
@select(df, c = a + b + rand())
```

what if I want to use the SAME`rand()` value for each row. Is there a way to do that?

**Comment by johnmyleswhite** [comment]
Yes, but perhaps not how you're thinking:

```
let x = rand()
    @select(df, c = a + b + $x)
end
```

**Comment by xiaodaigh** [comment]
I see. There is some planning involved. 

Is it possible to have some escaping mechanism like

```
    @select(df, c = a + b + $(rand()))
```

and everything inside `$` is only evaluated once by convention?

**Comment by johnmyleswhite** [comment]
Is the idea that

```
@select(df, c = a + b + $(rand()))

```

is translated into what amounts to 

```
let x = rand()
    @select(df, c = a + b + $x)
end
```

**Comment by xiaodaigh** [comment]
I guess so. One of the attraction of Volcanito for me is the convenience.  A `let` block is the opposite of that. If we auto-broadcast, then should have an easy to way escape auto-broadcasting in a row manner.

**Comment by johnmyleswhite** [comment]
>  A let block is the opposite of that

To be clear, you don't need a `let` block. Any local variable would work.

> If we auto-broadcast

This seems like a non-generic way to think of what's happening -- broadcasting is only an appropriate description for a columnar store with a well-defined row order. A much better mental model is iteration over rows; in that model, you're asking for a way to indicate that something should be forced to be loop invariant. But we have syntax for that in Julia: you take that piece of code out of the loop.

**Comment by xiaodaigh** [comment]
> you're asking for a way to indicate that something should be forced to be loop invariant

Would the loop approach have performance implications?

Would it be hard to implement something like `lead` and `lag`?

**Comment by johnmyleswhite** [comment]
> Would the loop approach have performance implications?

The loop approach is just a semantic model; if needed for performance, columnar operations could be used. But note that broadcasting itself is a tuple at a time operation, so it's not that different.

> Would it be hard to implement something like lead and lag?

These functions *are* very hard to implement in traditional databases. At some point I'll implement window functions to handle them: https://sqlite.org/windowfunctions.html

**Comment by xiaodaigh** [comment]
> These functions _are_ very hard to implement in traditional databases. At some point I'll implement window functions to handle them: https://sqlite.org/windowfunctions.html

It's only hard if you want a tool that is general and can work against any data-backend. in dplyr you can do

```
dataf %>%
  mutate(a = lead(a), b = lag(b))
```

say I have this function 

```
function fn(x::AbstractVector)
    x[1], x[end] = x[end], x[1]
end
```

This would work if the mental model is column-based, but if it's row-based. Would it work?

**Comment by johnmyleswhite** [comment]
I think you're confusing "is column-based" with "is ordered". They're distinct :) The whole trick of SQL window functions is to ensure there's a well-defined ordering -- and that matters even for columnar-formatted data like ORC.

What makes dplyr work the way it does is the conjunction of "operate on whole column at once" and "the column isn't going to shift its ordering underneath me". Both are not great assumptions for any API you might want to use for a distributed system.

**Comment by xiaodaigh** [comment]
> I think you're confusing "is column-based" with "is ordered". They're distinct :)



> It's only hard if you want a tool that is general and can work against any data-backend.

I haven't confused them. That's why I say the above.

If u remove that assumption then it becomes harder because as u say the db may not be ordered like an in-memory format. And also why windowing in SQL requires partition by and order by.

> "operate on whole column at once" and "the column isn't going to shift its ordering underneath me". Both are not great assumptions for any API you might want to use for a distributed system.

For a backend like DataFrames.jl we can assume those, and the question is **how to do something like what I mentioned**. We can save skip the partion over and order by in those cases by assuming the natural ordering as perf the memory layout.

**Comment by johnmyleswhite** [comment]
> For a backend like DataFrames.jl we can assume those, and the question is how to do something like what I mentioned. We can save skip the partion over and order by in those cases by assuming the natural ordering as perf the memory layout.

Ok, I should make clear that I'm not planning to support an API that operates in a special way on DataFrames.jl. There's enough people doing that already and it's not something I'm willing to spend my free time on. So my solution is precisely to follow the SQL tradition whenever I have time to get around to it and will require explicit order by/partition by specifications.

**Comment by xiaodaigh** [comment]
> So my solution is precisely to follow the SQL tradition whenever I have time to get around to it and will require explicit order by/partition by specifications.

Isn't leaving the partition by and order by undefined then it will just work for DataFrames.jl? Leaving them empty will throw an error for other db-types that require them. I don't see anything special that is needed for DataFrames.jl

```
function fn(x::AbstractVector)
    x[1], x[end] = x[end], x[1]
end
```

Back to the problem, even if you require partition by and order by for DataFrames.jl, how would I achieve it in Volcanito.jl. That is still not clear to me. Presumably, in SQL you would need to define another column that defines the order.

**Comment by johnmyleswhite** [comment]
> Isn't leaving the partition by and order by undefined then it will just work for DataFrames.jl?

I'm not a fan of undefined behaviors :)

**Comment by johnmyleswhite** [comment]
I'm going to close this thread. I appreciate the discussion, but it's a bit tangential from things I think are good uses of my time. There is a way to do what you originally asked and it's the only way to do it that I currently plan to support.
